# ------ root_path/dataset_name ------
root_path: 'your/data/path'


# ------ Load Cache and Features ------
load_cache: False
load_pre_feat: False

# ------ Hyperparamters ------
search_scale: [3, 7]
search_step: [20, 200]

init_beta: 1.0
init_alpha: 2.17


# ------ Basic Config ------
dataset: 'imagenet'
shots: 16
backbone: 'RN50'

thre: 0.3
loop: True
lr: 0.001
augment_epoch: 10
train_epoch: 20