# ------ root_path/dataset_name ------
root_path: 'your/data/path'


# ------ Load Cache and Features ------
load_cache: False
load_pre_feat: False

# ------ Hyperparamters ------
search_scale: [3, 20]
search_step: [20, 200]

init_beta: 2.32
init_alpha: 0.2

# ------ Basic Config ------
dataset: 'oxford_flowers'
shots: 1
backbone: 'RN50'

thre: 0.3
loop: False
lr: 0.001
augment_epoch: 10
train_epoch: 80